committee:
  - year: 2027
    venue: AGENT Workshop @ICSE 2027
    role: Program Committee
    url: https://conf.researchr.org/home/icse-2027/agent-2027

  - year: 2026
    venue: LLMSC Workshop @FSE 2026
    role: Publicity & Web Chair

  - year: 2025
    venue: LLMSC Workshop @ISSTA 2025
    role: Publicity & Web Chair

reviewer:
  - year: 2026
    venues:
      - TIFS
      - TDSC
      - IEEE T. Cybern.

  - year: 2025
    venues:
      - TDSC
      - TOSEM
      - TOPS
      - EMSE

sub_reviewer:
  - year: 2026
    venues:
      - USENIX Security
      - ASE
      - WWW
      - SIGCOMM

  - year: 2025
    venues:
      - S&P
      - FSE
      - ISSTA
      - ASE
      - NSDI
      - AsiaCCS
      - PoPETs
      - IWQoS

  - year: 2024
    venues:
      - CCS
      - FSE
      - ISSTA
      - WWW
      - IMC
      - Internetware
      - MSR
      - EASE
      - MobileSoft
      - SaTS
      - MobiLLM
      - LCTES
