committee:
  - year: 2027
    roles:
      - venue: LLMSC'27@ICSE
        role: Publicity & Web Chair
        url: https://llmsc.github.io/
      - venue: AGENT'27@ICSE
        role: Program Committee
        url: https://conf.researchr.org/home/icse-2027/agent-2027

  - year: 2026
    roles:
      - venue: CCS'26
        role: Artifact Evaluation Committee
        url: https://www.sigsac.org/ccs/CCS2026
      - venue: LLMSC'26@FSE
        role: Publicity & Web Chair
        url: https://llmsc.github.io/archive/26/

  - year: 2025
    roles:
      - venue: LLMSC'25@ISSTA
        role: Publicity & Web Chair
        url: https://llmsc.github.io/archive/25/

reviewer:
  - year: 2026
    venues:
      - TIFS
      - TDSC
      - TOSEM
      - IEEE T. Cybern.

  - year: 2025
    venues:
      - TDSC
      - TOSEM
      - TOPS
      - EMSE

sub_reviewer:
  - year: 2026
    venues:
      - USENIX Security
      - ASE
      - WWW
      - SIGCOMM

  - year: 2025
    venues:
      - S&P
      - FSE
      - ISSTA
      - ASE
      - NSDI
      - AsiaCCS
      - PoPETs
      - IWQoS

  - year: 2024
    venues:
      - CCS
      - FSE
      - ISSTA
      - WWW
      - IMC
      - Internetware
      - MSR
      - EASE
      - MobileSoft
      - SaTS
      - MobiLLM
      - LCTES
